[package]
name = "pretty-make"
version = "0.1.0"
authors = ["Awea <aweaoftheworld@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pest = "2.1.3"
pest_derive = "2.1.0"
